### ISSUE TITLE
Release to foxy

### ISSUE THREAD

**Issue by devrite** [open-rmf/ament_cmake_catch2#2]
## Feature request
Release to foxy
### Description
We would like to use it as an installable package in foxy. Guess it would still be useful to many?

### Alternatives
Users have it to integrate it on their own for foxy.

**Comment by marcoag** [comment]
You can find `eloquent` and `foxy` releases on this package in the rmf package repository:
http://rmf.servehttp.com

Instructions on how to use it are documented in the book here: 
https://osrf.github.io/ros2multirobotbook/#setup-sources-and-installation-of-rmf

However, since we are working on the process of releasing open-rmf packages for `galactic` into the official ros repos, it might make sense to do it for `foxy` too. I will leave this open until a decision is made on that direction.

**Comment by devrite** [comment]
Thx. I think it is already released to ros2 for galactic and rolling (at least the packages are there and the gbp repos exist). At least that is why we noticed it as some package uses it already and fails on foxy of course.

**Comment by marcoag** [comment]
This should be already released into foxy: 

https://build.ros2.org/view/Fbin_uF64/job/Fbin_uF64__ament_cmake_catch2__ubuntu_focal_amd64__binary/

Will proceed and close the issue.

**Comment by devrite** [comment]
Thx. Just checked it now appears in rosdep for foxy. The package itself seems to be not yet released to the official apt repo and probably will take until the next update cycle.
